sudo: required
language: generic

services:
    - docker
    
before_install:
    - docker build -t vinodres/windocker-react Dockerfile.dev .

script:
    - docker run -e CI=true vinodres/windocker-react npm run test